### ISSUE TITLE
[Question] Why Presto version is fixed to 0.174? Is there any limitations on HDInsight?

### ISSUE THREAD

**Issue by betarabbit** [dharmeshkakadia/presto-hdinsight#21]
Hi, this script action is awesome. 
I noticed the version of Presto is fixed to 0.174, but the latest release is 0.206, I am wondering why it need to be 0.174? Are there any limitations on HDInsight?

**Comment by dharmeshkakadia** [comment]
Thanks! I don't think there is anything specific in terms of version. You can just change the version on [line 18 of installpresto.sh](https://github.com/dharmeshkakadia/presto-hdinsight/blob/master/installpresto.sh#L18). The script was created when the latest version was 0.174. Since then I am no longer working with the team, I am not able to keep up the versions from upstream. 

Also, the team might be able to update the version if you raise request at https://github.com/hdinsight/presto-hdinsight/issues
